# Generated by Django 4.2.6 on 2023-10-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0009_rename_specialcontent_setting"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Link",
            new_name="Page",
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order"], "verbose_name": "page"},
        ),
        migrations.RemoveField(
            model_name="page",
            name="parent_link",
        ),
        migrations.AddField(
            model_name="page",
            name="parent_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="globals.page",
                verbose_name="parent page",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="hidden page"),
        ),
    ]
