# Generated by Django 4.2.6 on 2023-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0010_rename_link_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
    ]
