# Generated by Django 4.2.6 on 2023-10-20 16:17

import random
from django.db import migrations, models


def get_random_string():
    return hex(random.randrange(16**10))[2:]


def add_slugs(apps, schema_editor):
    Page = apps.get_model("globals", "Page")
    for page in Page.objects.all():
        page.slug = get_random_string()
        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0011_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(null=True, editable=False, max_length=100, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.RunPython(add_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
