# Generated by Django 5.0.6 on 2024-07-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
            ],
            options={
                "verbose_name": "special content",
                "verbose_name_plural": "special contents",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("hidden", models.BooleanField(default=False, verbose_name="hidden page")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("url", models.CharField(blank=True, max_length=100, verbose_name="URL")),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="globals.page",
                        verbose_name="parent page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "ordering": ["order"],
            },
        ),
    ]
