# Generated by Django 4.2 on 2023-06-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0004_alter_link_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="hidden link"),
        ),
        migrations.AlterField(
            model_name="link",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="link",
            name="parent_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="globals.link",
                verbose_name="parent link",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
    ]
