# Generated by Django 4.2.6 on 2023-10-19 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0008_alter_link_parent_link"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpecialContent",
            new_name="Setting",
        ),
    ]
