# Generated by Django 5.0.6 on 2024-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.IntegerField(unique=True, verbose_name="day")),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
            ],
            options={
                "verbose_name": "Day",
            },
        ),
    ]
