# Generated by Django 4.2.7 on 2023-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendrier_avent_2023", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="image"),
        ),
    ]
