# Generated by Django 5.1.2 on 2024-12-30 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorizedDelivering",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("recipient", models.CharField(max_length=255, verbose_name="Recipient")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Description")),
            ],
        ),
    ]
