# Generated by Django 4.2 on 2023-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('temperature', models.FloatField(verbose_name='Minimum temperature')),
                ('weather', models.CharField(choices=[('SUNNY', 'Sunny'), ('FEW_CLOUDS', 'Few clouds'), ('CLOUDY', 'Cloudy'), ('RAIN', 'Rain'), ('SNOW', 'Snow')], default='SUNNY', max_length=15, verbose_name='Weather')),
                ('wind', models.BooleanField(verbose_name='Wind')),
                ('hail', models.BooleanField(verbose_name='Hail')),
                ('mist', models.BooleanField(verbose_name='Mist')),
                ('snow_cm', models.PositiveIntegerField(default=0, verbose_name='snow cm')),
                ('max_temp', models.FloatField(blank=True, null=True, verbose_name='Maximum temperature')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'temperature',
                'ordering': ['date'],
            },
        ),
    ]
