# Generated by Django 4.2 on 2023-05-08 10:10

from django.db import migrations
import temperatures.fields


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='max_temp',
            field=temperatures.fields.TemperatureField(blank=True, null=True, verbose_name='Maximum temperature'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=temperatures.fields.TemperatureField(verbose_name='Minimum temperature'),
        ),
    ]
