# Generated by Django 4.2 on 2023-05-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_see_traceback', 'Can see traceback')], 'verbose_name': 'user'},
        ),
    ]
