# Generated by Django 4.0.6 on 2023-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL'),
        ),
    ]
