# Generated by Django 4.2 on 2023-04-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_page_rename_page_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order'], 'verbose_name': 'link'},
        ),
    ]
