# Generated by Django 4.2 on 2023-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_fix_caps_on_field_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
            ],
        ),
    ]
