# Generated by Django 4.2.3 on 2023-07-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="Session key"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(verbose_name="User agent")),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start time"
                    ),
                ),
                (
                    "expiry_time",
                    models.DateTimeField(verbose_name="Session expiry time"),
                ),
                ("time_on_site", models.IntegerField(verbose_name="Time on site")),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit",
                "ordering": ("-start_time",),
                "permissions": (("visitor_log", "Can view visitor"),),
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(verbose_name="URL")),
                ("referer", models.TextField(verbose_name="Referer")),
                ("query_string", models.TextField(verbose_name="Query string")),
                ("method", models.CharField(max_length=10, verbose_name="Method")),
                ("view_time", models.DateTimeField(verbose_name="View time")),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pageviews",
                        to="tracking.visit",
                        verbose_name="Visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "page view",
                "verbose_name_plural": "page views",
                "ordering": ("-view_time",),
            },
        ),
    ]
