# Generated by Django 4.2.3 on 2023-10-18 13:59

from django.db import migrations, models
import django.db.models.deletion
import storage.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="hidden page"),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", storage.fields.ImageField(upload_to="", verbose_name="image")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
    ]
