# Generated by Django 4.2.3 on 2023-10-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog", "0002_alter_page_content_alter_page_hidden_alter_page_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="image",
            name="content_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("file", models.FileField(upload_to="", verbose_name="file")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
